spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/home
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      max-lifetime: 300000
      idle-timeout: 600000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update   # or 'validate' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    de.inf_schauer.home_api: DEBUG
