spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/home
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update   # or 'validate' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    de.inf_schauer.home_api: DEBUG
